### GET Authors
GET https://localhost:7255/api/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5pc3RyYXRvciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiIyNjU1Mjc0YS0yODI5LTQwNTMtYTUxNS0wNjE1ZDdhYTZhMjMiLCJleHAiOjE3MzUyMTgyMzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjU1In0.ik-BJu9-LM2OObBGiKTw2q5vuOtgyc1QiZr0Pm1BmdI
Accept: application/json

### GET Authors With Filter
GET https://localhost:7255/api/authors?name=lorem&page=1&size=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5pc3RyYXRvciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiIyNjU1Mjc0YS0yODI5LTQwNTMtYTUxNS0wNjE1ZDdhYTZhMjMiLCJleHAiOjE3MzUyMTgyMzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjU1In0.ik-BJu9-LM2OObBGiKTw2q5vuOtgyc1QiZr0Pm1BmdI
Accept: application/json

### GET Author By Id
GET https://localhost:7255/api/authors/6753c6d8-64a1-4871-ac73-0e67b28fb79b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5pc3RyYXRvciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiIyNjU1Mjc0YS0yODI5LTQwNTMtYTUxNS0wNjE1ZDdhYTZhMjMiLCJleHAiOjE3MzUyMTgyMzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjU1In0.ik-BJu9-LM2OObBGiKTw2q5vuOtgyc1QiZr0Pm1BmdI
Accept: application/json

### POST Author
POST https://localhost:7255/api/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5pc3RyYXRvciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiIyNjU1Mjc0YS0yODI5LTQwNTMtYTUxNS0wNjE1ZDdhYTZhMjMiLCJleHAiOjE3MzUyMTgyMzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjU1In0.ik-BJu9-LM2OObBGiKTw2q5vuOtgyc1QiZr0Pm1BmdI
Accept: application/json
Content-Type: application/json

{
  "Name": "Name 1", 
  "Email": "user@domain.com" 
}

### PUT Author
PUT https://localhost:7255/api/authors/6753c6d8-64a1-4871-ac73-0e67b28fb79b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5pc3RyYXRvciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiIyNjU1Mjc0YS0yODI5LTQwNTMtYTUxNS0wNjE1ZDdhYTZhMjMiLCJleHAiOjE3MzUyMTgyMzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjU1In0.ik-BJu9-LM2OObBGiKTw2q5vuOtgyc1QiZr0Pm1BmdI
Accept: application/json
Content-Type: application/json

{
  "Name": "Name 1",
  "Email": "user@domain.com"
}

### DELETE Author
DELETE https://localhost:7255/api/authors/6753c6d8-64a1-4871-ac73-0e67b28fb79b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5pc3RyYXRvciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJzdWIiOiJhZG1pbmlzdHJhdG9yIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJqdGkiOiIyNjU1Mjc0YS0yODI5LTQwNTMtYTUxNS0wNjE1ZDdhYTZhMjMiLCJleHAiOjE3MzUyMTgyMzQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjU1In0.ik-BJu9-LM2OObBGiKTw2q5vuOtgyc1QiZr0Pm1BmdI
Accept: application/json